[project]
name = "pocket-dm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rcheong", email = "ryan.cheongtl@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
pocket-dm = "pocket_dm:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
