"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-27 23:19:43.777652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('system', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('setting', sa.String(), nullable=False),
    sa.Column('players', sa.JSON(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created', sa.String(), nullable=False),
    sa.Column('updated', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_table('characters',
    sa.Column('campaign_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('player', sa.String(), nullable=False),
    sa.Column('race', sa.String(), nullable=False),
    sa.Column('background', sa.String(), nullable=False),
    sa.Column('alignment', sa.String(), nullable=False),
    sa.Column('classes', sa.JSON(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('abilities', sa.JSON(), nullable=False),
    sa.Column('save_proficiencies', sa.JSON(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('jack_of_all_trades', sa.Boolean(), nullable=False),
    sa.Column('ac', sa.Integer(), nullable=False),
    sa.Column('initiative_misc', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('hp', sa.JSON(), nullable=False),
    sa.Column('hit_dice', sa.JSON(), nullable=False),
    sa.Column('death_saves', sa.JSON(), nullable=False),
    sa.Column('inspiration', sa.Boolean(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('exhaustion', sa.Integer(), nullable=False),
    sa.Column('proficiencies', sa.JSON(), nullable=False),
    sa.Column('attacks', sa.JSON(), nullable=False),
    sa.Column('spellcasting', sa.JSON(), nullable=False),
    sa.Column('resources', sa.JSON(), nullable=False),
    sa.Column('inventory', sa.JSON(), nullable=False),
    sa.Column('currency', sa.JSON(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('personality', sa.JSON(), nullable=False),
    sa.Column('appearance', sa.String(), nullable=False),
    sa.Column('backstory', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created', sa.String(), nullable=False),
    sa.Column('updated', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_characters_campaign_id_campaigns'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_characters'))
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_characters_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('handbook',
    sa.Column('campaign_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created', sa.String(), nullable=False),
    sa.Column('updated', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_handbook_campaign_id_campaigns'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_handbook'))
    )
    with op.batch_alter_table('handbook', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_handbook_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('sessions',
    sa.Column('campaign_id', sa.String(length=64), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attendance', sa.JSON(), nullable=False),
    sa.Column('prep', sa.String(), nullable=False),
    sa.Column('recap', sa.String(), nullable=False),
    sa.Column('log', sa.JSON(), nullable=False),
    sa.Column('encounter', sa.JSON(), nullable=False),
    sa.Column('loot', sa.JSON(), nullable=False),
    sa.Column('xp_awarded', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created', sa.String(), nullable=False),
    sa.Column('updated', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_sessions_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_campaign_id'), ['campaign_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_campaign_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('handbook', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_handbook_campaign_id'))

    op.drop_table('handbook')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_characters_campaign_id'))

    op.drop_table('characters')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
